### PR TITLE
Print name of file that is "Unknown AppImage format", closes #102

### LINKED ISSUE #102: ERROR: appimage_get_type : Unknown AppImage format
Getting lots of 

```
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
ERROR: appimage_get_type : Unknown AppImage format
```

It would be useful if the filename was printed too, to make some sense of the output.

```
appimaged, continuous build (commit 2e34378), build 108 built on 2019-03-14 17:43:20 UTC
```

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

File: src/libappimage/core/AppImage.cpp [hunk 1]
```diff
@@ -41,7 +41,7 @@ namespace appimage {
             format = getFormat(path);
 
             if (format == AppImageFormat::INVALID)
-                throw core::AppImageError("Unknown AppImage format");
+                throw core::AppImageError("Unknown AppImage format: "  << path);
```
Comment (TheAssassin) [inline src/libappimage/core/AppImage.cpp]: You can't use stream operators on arbitrary strings. Also, there's two spaces. Please just use `+`. If path is a `boost::filesystem::path`, use `path.string()`.

Comment (probonopd) [reply src/libappimage/core/AppImage.cpp]: Why does this work in Qt but not here? I am absolutely not a C++ guy...

Comment (TheAssassin) [reply src/libappimage/core/AppImage.cpp]: This also doesn't work in Qt that way. There may be more stream magic, e.g., Qt might have implemented a `<<` operator for their own `QString` class that works with left-hand arguments, but you're using `std::string` here.
Qt is not standard C++, it's often like a language put on top of C++. This here, however, is standard C++11.

Comment (probonopd) [reply src/libappimage/core/AppImage.cpp]: Which brings me to the point why we are using C++ and Boost rather than Qt? (Not saying we should switch immediately, but just curious.)

Comment (TheAssassin) [reply src/libappimage/core/AppImage.cpp]: This issue here is just about `std::string`, note the `std`. Boost is fast, convenient, mostly imported in the STL later on anyway (so when going for newer standards you can just `s/boost/std` in many cases), ...

Not using Qt allows non-Qt desktops to use this without political discussions.

**Comment by probonopd** [comment]
No clue why the test fails now.

**Comment by TheAssassin** [comment]
You can't simply remove exceptions. They're part of a function's contract. This exception is expected to be thrown by the unit tests. You must restore that behavior.

**Comment by probonopd** [comment]
I wondered why in this location the error message printing works different than in other similar-looking places a few lines below. I think it is inconsistent, and wanted to make it more consistent with other warnings.

**Comment by probonopd** [comment]
This seems to have worked, at least the build succeeded. Now, how do I test this with appimagetool? (Before everything was split into multiple repositories, this PR would have built a new appimagetool too, point in case for why I want a [monorepo](https://github.com/AppImage/AppImageKit/issues/931).)

**Comment by probonopd** [comment]
Feel free to revert if this breaks something.
